### ISSUE TITLE
Add template config information to README.md

### ISSUE THREAD

**Issue by edaena** [andrewDoing/hydrate#17]
As a user I want to view in the README.md the information about the options for the component.yaml

- [ ] link to the description in the fabrikate repo

- [ ] add some of the options directly in the README.md (optional)

**Comment by andrewDoing** [comment]
Currently the component.yaml fields are defined inside the HLD class. However, due to python's ability to dynamically add attributes to objects, the fields could be created from a custom configuration. This configuration could come from a text file or the user.

It would be useful to allow this so that the user has more control over the component.yaml.
